### ISSUE TITLE
Regression: action fails if no tags yet

### ISSUE THREAD

**Issue by cjmaxik** [fregante/daily-version-action#28]
It looks like there is a regression of #18 

```
Run fregante/daily-version-action@v2
  with:
  env:
    DIRECTORY: distribution
Error: Error Command failed: git fetch --depth=1 origin refs/tags/*:refs/tags/*
````

**Comment by fregante** [comment]
That's unlikely since no changes were made in that area. 

Are you using action/checkout before this daily-version-action?

**Comment by cjmaxik** [comment]
I do, yes. I use the same `release.yml` as in your browser extension template.

**Comment by fregante** [comment]
Thanks for the report! It has been broken for a while 🥲
