### ISSUE TITLE
Update Node.js 16 to Node.js 20

### ISSUE THREAD

**Issue by MasterZydra** [fregante/daily-version-action#32]
Hi @fregante,

Can you please update your Node.js version from 16 to 20?

GitHub shows me the following warning when using your action:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: fregante/daily-version-action@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by fregante** [comment]
PR welcome

**Comment by MasterZydra** [comment]
Hi @fregante,

I have never updated or created a GitHub action step, I just used them. I hope the version update is correct.

**Comment by MasterZydra** [comment]
Thanks for merging the PR. The warning is now gone :+1:
